name: Deploy CaronaApp
on:
  push:
    branches: ["main"] # Verifique se sua branch é 'main' ou 'master'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Código
        uses: actions/checkout@v4

      - name: Injetar Chave Secreta
        env:
          # Carrega o segredo para uma variável de ambiente primeiro
          FIREBASE_JSON: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          # Usa PERL em vez de SED (Perl aceita quebras de linha no JSON)
          perl -i -pe 's|FIREBASE_CONFIG_PLACEHOLDER|$ENV{FIREBASE_JSON}|g' index.html

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Upload do Site
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Publicar
        id: deployment
        uses: actions/deploy-pages@v4
